name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: 'https://ericmuir@bitbucket.org/swimcloud-project/terraform-aws-base-instance.git'
        ssh-key: ${{ secrets.SSH_KEY }}
        path: terraform-aws-base-instance
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag contributions:$GITHUB_SHA
