name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: ebdmuir/contributions
        path: contributions
    - name: Add git config
      run: git config --global user.name "Eric Muir" && git config --global user.email "hello@ebdm.dev"
    - name: Install Dependancies
      run: pip3 install gitpython pathlib
    - name: Run script
      run: echo $REPOS && python3 run.py
      env:
        REPOS: ${{ secrets.REPOS }}
        EMAILS: ${{ secrets.EMAILS }}
    - name: Push changes
      run: cd contributions && git push --force "https://${{ env.GIT_USERNAME }}:${{ secrets.GH_ACCESS_TOKEN }}@${{ secrets.EXPORT_REPO }}"