name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - uses: actions/checkout@v2
    - name: Fetch terraform-aws-base-instance
      run: git clone https://ericmuir@bitbucket.org/swimcloud-project/terraform-aws-base-instance.git
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag contributions:$GITHUB_SHA
    - name: Run the Docker image
      run: docker run contributions:$GITHUB_SHA