name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: ebdmuir/contributions
        path: contributions
    - name: Fetch terraform-aws-base-instance
      run: git clone git@bitbucket.org:swimcloud-project/terraform-aws-base-instance.git
    - run: ls
    - name: Install Dependancies
      run: pip3 install gitpython pathlib
    - name: Run script
      run: python3 run.py